services:
  blog-notifier:
    build: .
    environment:
      - CHAT_WEBHOOK=${CHAT_WEBHOOK}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud